name: TagAndRelease

on:
  push:
    branches:
    - master

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@master
      env:
        DEFAULT_BUMP: patch
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_OWNER: ace-teknologi
        WITH_V: true
  release:
    strategy:
      matrix:
        goarch: ["386", "amd64"]
        goos: ["darwin", "linux", "windows"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Compile and release
      uses: ngs/go-release.action@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: ${{ matrix.goarch }}
        GOOS: ${{ matrix.goos }}
